package it.enea.lecop.eca.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.TextField;

public class CalculatePanel extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private NativeButton nativeButton_1;
	@AutoGenerated
	private TextField textField_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CalculatePanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(true);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		mainLayout.addComponent(textField_1, "top:160.0px;left:203.0px;");
		
		// nativeButton_1
		nativeButton_1 = new NativeButton();
		nativeButton_1.setCaption("Calcola");
		nativeButton_1.setImmediate(false);
		nativeButton_1.setWidth("-1px");
		nativeButton_1.setHeight("-1px");
		mainLayout.addComponent(nativeButton_1, "top:162.0px;left:50.0px;");
		
		return mainLayout;
	}

	@Override
	public String getCaption() {
		// TODO Auto-generated method stub
		return nativeButton_1.getCaption();
	}
}
