package it.enea.lecop.eca.model;

// Generated 20-mar-2012 12.10.19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Access;
import static javax.persistence.AccessType.FIELD;
import static javax.persistence.AccessType.PROPERTY;
import javax.persistence.NamedNativeQuery;
import javax.persistence.Cacheable;
import javax.persistence.DiscriminatorColumn;
import static javax.persistence.DiscriminatorType.CHAR;
import static javax.persistence.DiscriminatorType.INTEGER;
import static javax.persistence.DiscriminatorType.STRING;
import javax.persistence.QueryHint;


/**
 * Comuni generated by hbm2java
 */
@Entity
@NamedQueries({
    @NamedQuery(name="Comune.findAll",
                query="SELECT u FROM Comune u"),
    @NamedQuery(name="Comune.findById",
                query="SELECT u FROM Comune u WHERE u.id = :id"),
 
   @NamedQuery(name="Comune.findAllOWNERUSER",
         query="SELECT u FROM Comune u WHERE (u.ownerid.ownUser.username = :username) and (" +
   		       "(u.permissionprop.OWNERUSER = :ownuserSec1) or " +
   		       "(u.permissionprop.OWNERUSER = :ownuserSec2) or " +
   		       "(u.permissionprop.OWNERUSER = :ownuserSec3) or " +
   		       "(u.permissionprop.OWNERUSER = :ownuserSec4))"), 
    @NamedQuery(name="Comune.findAllOWNDOMAIN",
            query="SELECT u FROM Comune u WHERE (u.ownerid.ownCompany.name = :domainname) and (" +
      		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec1) or " +
      		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec2) or " +
      		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec3) or " +
      		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec4))"),
    @NamedQuery(name="Comune.findAllNO_OWNERUSEROWNDOMAIN",
                 query="SELECT u FROM Comune u WHERE (u.ownerid.ownCompany.name <> :domainname) " +
                 		"and (u.ownerid.ownUser.username <> :username)"),
    @NamedQuery(name="Comune.findAllOWNERUSER_OWNDOMAIN",
                        query="SELECT u FROM Comune u WHERE (:username = 'admin') or((u.ownerid.ownUser.username = :username) and (" +
                    		       "(u.permissionprop.OWNERUSER = :ownuserSec1) or " +
                       		       "(u.permissionprop.OWNERUSER = :ownuserSec2) or " +
                       		       "(u.permissionprop.OWNERUSER = :ownuserSec3) or " +
                       		       "(u.permissionprop.OWNERUSER = :ownuserSec4)))" +
                       		       " or (" +
                       		       "(u.ownerid.ownCompany.name = :domainname) and (" +
                       		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec1) or " +
                       		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec2) or " +
                       		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec3) or " +
                       		       "(u.permissionprop.IDENTITYDOMAIN = :owndomainSec4)))" +
                       		       "or (u.permissionprop.OTHER IN (:otherSec1 , :otherSec2 , :otherSec3 , :otherSec4))")  
                  		       
   //  @NamedQuery(name = "Comune.findAllOWNERUSER", query = "select u from Comune u where (u.ownerid.ownUser.username = :username) and ((u.permissionprop.OWNERUSER = :ownuserSec1) or (u.permissionprop.OWNERUSER = :ownuserSec2) or (u.permissionprop.OWNERUSER = :ownuserSec3) or (u.permissionprop.OWNERUSER = :ownuserSec4))")          		
})

@Table(name = "comuni")
@Cacheable(false)
public class Comune implements java.io.Serializable, Securable
{

   /* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((altitudine == null) ? 0 : altitudine.hashCode());
		result = prime * result
				+ ((codiceIstat == null) ? 0 : codiceIstat.hashCode());
		result = prime * result
				+ ((descrizione == null) ? 0 : descrizione.hashCode());
		result = prime * result
				+ ((gradigiorno == null) ? 0 : gradigiorno.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((idRegione == null) ? 0 : idRegione.hashCode());
		result = prime * result
				+ ((latitudine == null) ? 0 : latitudine.hashCode());
		result = prime * result
				+ ((longitudine == null) ? 0 : longitudine.hashCode());
		result = prime * result + ((presAgo == null) ? 0 : presAgo.hashCode());
		result = prime * result + ((presApr == null) ? 0 : presApr.hashCode());
		result = prime * result + ((presDic == null) ? 0 : presDic.hashCode());
		result = prime * result + ((presFeb == null) ? 0 : presFeb.hashCode());
		result = prime * result + ((presGen == null) ? 0 : presGen.hashCode());
		result = prime * result + ((presGiu == null) ? 0 : presGiu.hashCode());
		result = prime * result + ((presLug == null) ? 0 : presLug.hashCode());
		result = prime * result + ((presMag == null) ? 0 : presMag.hashCode());
		result = prime * result + ((presMar == null) ? 0 : presMar.hashCode());
		result = prime * result + ((presNov == null) ? 0 : presNov.hashCode());
		result = prime * result + ((presOtt == null) ? 0 : presOtt.hashCode());
		result = prime * result + ((presSet == null) ? 0 : presSet.hashCode());
		result = prime * result + ((prov1 == null) ? 0 : prov1.hashCode());
		result = prime * result + ((prov2 == null) ? 0 : prov2.hashCode());
		result = prime * result
				+ ((provincia == null) ? 0 : provincia.hashCode());
		result = prime * result
				+ ((tempEsterna == null) ? 0 : tempEsterna.hashCode());
		result = prime * result + ((zona == null) ? 0 : zona.hashCode());
		result = prime * result + ((zonaGeo == null) ? 0 : zonaGeo.hashCode());
		result = prime * result
				+ ((zonaVento == null) ? 0 : zonaVento.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		
		//System.out.println("Equals Comune");
		//System.out.flush();
		
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Comune))
			return false;
		Comune other = (Comune) obj;
		if(id== other.id) return true;
		
		if (altitudine == null) {
			if (other.altitudine != null)
				return false;
		} else if (!altitudine.equals(other.altitudine))
			return false;
		if (codiceIstat == null) {
			if (other.codiceIstat != null)
				return false;
		} else if (!codiceIstat.equals(other.codiceIstat))
			return false;
		if (descrizione == null) {
			if (other.descrizione != null)
				return false;
		} else if (!descrizione.equals(other.descrizione))
			return false;
		if (gradigiorno == null) {
			if (other.gradigiorno != null)
				return false;
		} else if (!gradigiorno.equals(other.gradigiorno))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (idRegione == null) {
			if (other.idRegione != null)
				return false;
		} else if (!idRegione.equals(other.idRegione))
			return false;
		if (latitudine == null) {
			if (other.latitudine != null)
				return false;
		} else if (!latitudine.equals(other.latitudine))
			return false;
		if (longitudine == null) {
			if (other.longitudine != null)
				return false;
		} else if (!longitudine.equals(other.longitudine))
			return false;
		if (presAgo == null) {
			if (other.presAgo != null)
				return false;
		} else if (!presAgo.equals(other.presAgo))
			return false;
		if (presApr == null) {
			if (other.presApr != null)
				return false;
		} else if (!presApr.equals(other.presApr))
			return false;
		if (presDic == null) {
			if (other.presDic != null)
				return false;
		} else if (!presDic.equals(other.presDic))
			return false;
		if (presFeb == null) {
			if (other.presFeb != null)
				return false;
		} else if (!presFeb.equals(other.presFeb))
			return false;
		if (presGen == null) {
			if (other.presGen != null)
				return false;
		} else if (!presGen.equals(other.presGen))
			return false;
		if (presGiu == null) {
			if (other.presGiu != null)
				return false;
		} else if (!presGiu.equals(other.presGiu))
			return false;
		if (presLug == null) {
			if (other.presLug != null)
				return false;
		} else if (!presLug.equals(other.presLug))
			return false;
		if (presMag == null) {
			if (other.presMag != null)
				return false;
		} else if (!presMag.equals(other.presMag))
			return false;
		if (presMar == null) {
			if (other.presMar != null)
				return false;
		} else if (!presMar.equals(other.presMar))
			return false;
		if (presNov == null) {
			if (other.presNov != null)
				return false;
		} else if (!presNov.equals(other.presNov))
			return false;
		if (presOtt == null) {
			if (other.presOtt != null)
				return false;
		} else if (!presOtt.equals(other.presOtt))
			return false;
		if (presSet == null) {
			if (other.presSet != null)
				return false;
		} else if (!presSet.equals(other.presSet))
			return false;
		if (prov1 == null) {
			if (other.prov1 != null)
				return false;
		} else if (!prov1.equals(other.prov1))
			return false;
		if (prov2 == null) {
			if (other.prov2 != null)
				return false;
		} else if (!prov2.equals(other.prov2))
			return false;
		if (provincia == null) {
			if (other.provincia != null)
				return false;
		} else if (!provincia.equals(other.provincia))
			return false;
		if (tempEsterna == null) {
			if (other.tempEsterna != null)
				return false;
		} else if (!tempEsterna.equals(other.tempEsterna))
			return false;
		if (zona == null) {
			if (other.zona != null)
				return false;
		} else if (!zona.equals(other.zona))
			return false;
		if (zonaGeo == null) {
			if (other.zonaGeo != null)
				return false;
		} else if (!zonaGeo.equals(other.zonaGeo))
			return false;
		if (zonaVento == null) {
			if (other.zonaVento != null)
				return false;
		} else if (!zonaVento.equals(other.zonaVento))
			return false;
		return true;
	}

/**
    * 
    */
  
   private Long id;
   private Integer idRegione;
   private String descrizione;
   private String provincia;
   private Double altitudine;
   private String zona;
   private Integer gradigiorno;
   private Double tempEsterna;
   private Double latitudine;
   private Double longitudine;
   private Integer zonaVento;
   private Integer zonaGeo;
   private String prov1;
   private String prov2;
   private Integer presGen;
   private Integer presFeb;
   private Integer presMar;
   private Integer presApr;
   private Integer presMag;
   private Integer presGiu;
   private Integer presLug;
   private Integer presAgo;
   private Integer presSet;
   private Integer presOtt;
   private Integer presNov;
   private Integer presDic;
   private String codiceIstat;


  



public Comune()
   {
   }

   public Comune(Long id)
   {
      this.id = id;
   }

   public Comune(Long id, Integer idRegione, String descrizione, String provincia, Double altitudine, String zona, Integer gradigiorno, Double tempEsterna, Double latitudine, Double longitudine, Integer zonaVento, Integer zonaGeo, String prov1, String prov2, Integer presGen, Integer presFeb, Integer presMar, Integer presApr, Integer presMag, Integer presGiu, Integer presLug, Integer presAgo, Integer presSet, Integer presOtt, Integer presNov, Integer presDic, String codiceIstat)
   {
      this.id = id;
      this.idRegione = idRegione;
      this.descrizione = descrizione;
      this.provincia = provincia;
      this.altitudine = altitudine;
      this.zona = zona;
      this.gradigiorno = gradigiorno;
      this.tempEsterna = tempEsterna;
      this.latitudine = latitudine;
      this.longitudine = longitudine;
      this.zonaVento = zonaVento;
      this.zonaGeo = zonaGeo;
      this.prov1 = prov1;
      this.prov2 = prov2;
      this.presGen = presGen;
      this.presFeb = presFeb;
      this.presMar = presMar;
      this.presApr = presApr;
      this.presMag = presMag;
      this.presGiu = presGiu;
      this.presLug = presLug;
      this.presAgo = presAgo;
      this.presSet = presSet;
      this.presOtt = presOtt;
      this.presNov = presNov;
      this.presDic = presDic;
      this.codiceIstat = codiceIstat;
   }

   @Id
   @Column(name = "ID", unique = true, nullable = false)
   public Long getId()
   {
      return this.id;
   }

   
   
   
   
   
   public void setId(Long id)
   {
      this.id = id;
   }

   @Column(name = "regione")
   public Integer getIdRegione()
   {
      return this.idRegione;
   }

   public void setIdRegione(Integer idRegione)
   {
      this.idRegione = idRegione;
   }

   @Column(name = "Descrizione", length = 50)
   public String getDescrizione()
   {
      return this.descrizione;
   }

   public void setDescrizione(String descrizione)
   {
      this.descrizione = descrizione;
   }

   @Column(name = "Provincia", length = 2)
   public String getProvincia()
   {
      return this.provincia;
   }

   public void setProvincia(String provincia)
   {
      this.provincia = provincia;
   }

   @Column(name = "Altitudine", precision = 22, scale = 0)
   public Double getAltitudine()
   {
      return this.altitudine;
   }

   public void setAltitudine(Double altitudine)
   {
      this.altitudine = altitudine;
   }

   @Column(name = "Zona", length = 1)
   public String getZona()
   {
      return this.zona;
   }

   public void setZona(String zona)
   {
      this.zona = zona;
   }

   @Column(name = "Gradigiorno")
   public Integer getGradigiorno()
   {
      return this.gradigiorno;
   }

   public void setGradigiorno(Integer gradigiorno)
   {
      this.gradigiorno = gradigiorno;
   }

   @Column(name = "TempEsterna", precision = 22, scale = 0)
   public Double getTempEsterna()
   {
      return this.tempEsterna;
   }

   public void setTempEsterna(Double tempEsterna)
   {
      this.tempEsterna = tempEsterna;
   }

   @Column(name = "Latitudine", precision = 22, scale = 0)
   public Double getLatitudine()
   {
      return this.latitudine;
   }

   public void setLatitudine(Double latitudine)
   {
      this.latitudine = latitudine;
   }

   @Column(name = "Longitudine", precision = 22, scale = 0)
   public Double getLongitudine()
   {
      return this.longitudine;
   }

   public void setLongitudine(Double longitudine)
   {
      this.longitudine = longitudine;
   }

   @Column(name = "ZonaVento")
   public Integer getZonaVento()
   {
      return this.zonaVento;
   }

   public void setZonaVento(Integer zonaVento)
   {
      this.zonaVento = zonaVento;
   }

   @Column(name = "ZonaGeo")
   public Integer getZonaGeo()
   {
      return this.zonaGeo;
   }

   public void setZonaGeo(Integer zonaGeo)
   {
      this.zonaGeo = zonaGeo;
   }

   @Column(name = "Prov1", length = 2)
   public String getProv1()
   {
      return this.prov1;
   }

   public void setProv1(String prov1)
   {
      this.prov1 = prov1;
   }

   @Column(name = "Prov2", length = 2)
   public String getProv2()
   {
      return this.prov2;
   }

   public void setProv2(String prov2)
   {
      this.prov2 = prov2;
   }

   @Column(name = "PresGen")
   public Integer getPresGen()
   {
      return this.presGen;
   }

   public void setPresGen(Integer presGen)
   {
      this.presGen = presGen;
   }

   @Column(name = "PresFeb")
   public Integer getPresFeb()
   {
      return this.presFeb;
   }

   public void setPresFeb(Integer presFeb)
   {
      this.presFeb = presFeb;
   }

   @Column(name = "PresMar")
   public Integer getPresMar()
   {
      return this.presMar;
   }

   public void setPresMar(Integer presMar)
   {
      this.presMar = presMar;
   }

   @Column(name = "PresApr")
   public Integer getPresApr()
   {
      return this.presApr;
   }

   public void setPresApr(Integer presApr)
   {
      this.presApr = presApr;
   }

   @Column(name = "PresMag")
   public Integer getPresMag()
   {
      return this.presMag;
   }

   public void setPresMag(Integer presMag)
   {
      this.presMag = presMag;
   }

   @Column(name = "PresGiu")
   public Integer getPresGiu()
   {
      return this.presGiu;
   }

   public void setPresGiu(Integer presGiu)
   {
      this.presGiu = presGiu;
   }

   @Column(name = "PresLug")
   public Integer getPresLug()
   {
      return this.presLug;
   }

   public void setPresLug(Integer presLug)
   {
      this.presLug = presLug;
   }

   @Column(name = "PresAgo")
   public Integer getPresAgo()
   {
      return this.presAgo;
   }

   public void setPresAgo(Integer presAgo)
   {
      this.presAgo = presAgo;
   }

   @Column(name = "PresSet")
   public Integer getPresSet()
   {
      return this.presSet;
   }

   public void setPresSet(Integer presSet)
   {
      this.presSet = presSet;
   }

   @Column(name = "PresOtt")
   public Integer getPresOtt()
   {
      return this.presOtt;
   }

   public void setPresOtt(Integer presOtt)
   {
      this.presOtt = presOtt;
   }

   @Column(name = "PresNov")
   public Integer getPresNov()
   {
      return this.presNov;
   }

   public void setPresNov(Integer presNov)
   {
      this.presNov = presNov;
   }

   @Column(name = "PresDic")
   public Integer getPresDic()
   {
      return this.presDic;
   }

   public void setPresDic(Integer presDic)
   {
      this.presDic = presDic;
   }

   @Column(name = "CodiceISTAT", length = 6)
   public String getCodiceIstat()
   {
      return this.codiceIstat;
   }

   public void setCodiceIstat(String codiceIstat)
   {
      this.codiceIstat = codiceIstat;
   }
/*
   @ManyToOne
   @NotNull
   private CompanyDomain defaultSecurityDomain;



   public CompanyDomain getDefaultSecurityDomain() {
   	return defaultSecurityDomain;
   }

   public void setDefaultSecurityDomain(CompanyDomain defaultSecurityDomain) {
   	this.defaultSecurityDomain = defaultSecurityDomain;
   }
  */
   
   private OwnerId ownerid;
   private PermissionProp permissionprop;
   
   @Embedded
   public OwnerId getOwnerid()
   {
	  
	return ownerid;
   }
   
   public void setOwnerid(OwnerId ownerid) {
		this.ownerid = ownerid;
	}
   
   @Embedded
   public PermissionProp getPermissionprop()
   {
	   return permissionprop;
   }
   
   public void setPermissionprop(PermissionProp permissionprop) {
		this.permissionprop = permissionprop;
	}
   
   
   
}
